export const REQUEST_DATA = 'REQUEST_DATA';

export const RECEIVE_INITIAL_DATA = 'RECEIVE_INITIAL_DATA';
export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';
export const RECEIVE_MORE_DATA = 'RECEIVE_MORE_DATA';

export const RECEIVE_CONNECTION = 'RECEIVE_CONNECTION';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';
