export const REQUEST_DATA = 'REQUEST_DATA';

export const RECEIVE_INITIAL_DATA = 'RECEIVE_INITIAL_DATA';
export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';
export const RECEIVE_MORE_DATA = 'RECEIVE_MORE_DATA';

export const RECEIVE_CONNECTION = 'RECEIVE_CONNECTION';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';

export const STREAM_TRACK = 'STREAM_TRACK';
export const PLAY_TRACK = 'PLAY_TRACK';
export const RESUME_TRACK = 'RESUME_TRACK';
export const PAUSE_TRACK = 'PAUSE_TRACK';
export const CHANGE_VOLUME = 'CHANGE_VOLUME';
export const UPDATE_TRACK_POSITION = 'UPDATE_TRACK_POSITION';
